// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTwlQR3chMWQAvfUVZG60lsWAf8oO8E-k',
    appId: '1:861530547500:web:21bc082e44a9b1f0f33889',
    messagingSenderId: '861530547500',
    projectId: 'hackharvard2022-4724b',
    authDomain: 'hackharvard2022-4724b.firebaseapp.com',
    databaseURL: 'https://hackharvard2022-4724b-default-rtdb.firebaseio.com',
    storageBucket: 'hackharvard2022-4724b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfD72FaPNr5UO2PD3gXGIZ_teS8BbBCbA',
    appId: '1:861530547500:android:6db897c431b463c1f33889',
    messagingSenderId: '861530547500',
    projectId: 'hackharvard2022-4724b',
    databaseURL: 'https://hackharvard2022-4724b-default-rtdb.firebaseio.com',
    storageBucket: 'hackharvard2022-4724b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7LWqtBsEYJXhknnKznvr0O9i6b6H-ltk',
    appId: '1:861530547500:ios:afc4c20bb3b2b1d6f33889',
    messagingSenderId: '861530547500',
    projectId: 'hackharvard2022-4724b',
    databaseURL: 'https://hackharvard2022-4724b-default-rtdb.firebaseio.com',
    storageBucket: 'hackharvard2022-4724b.appspot.com',
    iosClientId: '861530547500-jjlok8h8se90ojpt1oaj543peheq9up9.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7LWqtBsEYJXhknnKznvr0O9i6b6H-ltk',
    appId: '1:861530547500:ios:afc4c20bb3b2b1d6f33889',
    messagingSenderId: '861530547500',
    projectId: 'hackharvard2022-4724b',
    databaseURL: 'https://hackharvard2022-4724b-default-rtdb.firebaseio.com',
    storageBucket: 'hackharvard2022-4724b.appspot.com',
    iosClientId: '861530547500-jjlok8h8se90ojpt1oaj543peheq9up9.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );
}
